version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: curl --fail http://127.0.0.1:3306 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
volumes:
  dbdata: