version: '3.4'

services:
  db:
    container_name: posgres_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: curl --fail http://0.0.0.0:3306 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
volumes:
  dbdata:
    driver: local