version: '3.4'

services:
  bak.api:
    container_name: api_client
    image: bakapi
    build:
      context: .
      dockerfile: bak.api/Dockerfile
    volumes:
      - apidata:/tmp/
    ports:
      - "5002:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_ISSUER: vetsys
      JWT_KEY: K_S_7ZlkWpc_w_JkihksIQ
volumes:
  apidata:
    driver: local